### ISSUE TITLE
'NotificationType' is not JSON serializable

### ISSUE THREAD

**Issue by vincent-paing** [Cretezy/pymessenger2#20]
When calling quick reply, I keep getting this error

```
File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymessenger2/bot.py", line 200, in send_quick_reply
    }, notification_type)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymessenger2/bot.py", line 76, in send_message
    notification_type)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymessenger2/bot.py", line 69, in send_recipient
    return self.send_raw(payload)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymessenger2/bot.py", line 395, in send_raw
    data=json.dumps(payload, cls=AttrsEncoder),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pymessenger2/utils.py", line 58, in default
    return json.JSONEncoder.default(self, obj)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'NotificationType' is not JSON serializable

```

**Comment by jersobh** [comment]
I'm still getting this error
TypeError: Object of type 'NotificationType' is not JSON serializable

{'sender': {'id': '408950186184485'}, 'recipient': {'id': '1893175587420559'}, 'timestamp': 1522167654679, 'message': {'is_echo': True, 'mid': 'mid.$cAAFz8B62LINomYhxF1iaEYXxBR0g', 'seq': 66566, 'text': 'help'}}
message:
help
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "server.py", line 38, in middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 132, in factory
    response = await handler(request)
  File "/home/ec2-user/vidmonsters-api/integrations/facebook.py", line 82, in webhook
    bot.send_quick_reply(recipient_id,"Olá", talk_categories)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 200, in send_quick_reply
    }, notification_type)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 76, in send_message
    notification_type)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 69, in send_recipient
    return self.send_raw(payload)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 395, in send_raw
    data=json.dumps(payload, cls=AttrsEncoder),
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/utils.py", line 58, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'NotificationType' is not JSON serializable
{'sender': {'id': '408950186184485'}, 'recipient': {'id': '1893175587420559'}, 'timestamp': 1522167654679, 'message': {'is_echo': True, 'mid': 'mid.$cAAFz8B62LINomYhxF1iaEYXxBR0g', 'seq': 66566, 'text': 'help'}}
message:
help
Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 410, in start
    resp = yield from self._request_handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "server.py", line 38, in middleware
    return await handler(request)
  File "/usr/local/lib/python3.6/site-packages/aiohttp_session/__init__.py", line 132, in factory
    response = await handler(request)
  File "/home/ec2-user/vidmonsters-api/integrations/facebook.py", line 82, in webhook
    bot.send_quick_reply(recipient_id,"Olá", talk_categories)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 200, in send_quick_reply
    }, notification_type)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 76, in send_message
    notification_type)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 69, in send_recipient
    return self.send_raw(payload)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/bot.py", line 395, in send_raw
    data=json.dumps(payload, cls=AttrsEncoder),
  File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.6/site-packages/pymessenger2/utils.py", line 58, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'NotificationType' is not JSON serializable

**Comment by vincent-paing** [comment]
@jersobh  I don't think it's been added to release version yet. Just add .value like I did in my Pull Request #21
